import type { Metadata } from 'next';
import './globals.css';
import { PagesProvider } from '@/store/pages-context';

export const metadata: Metadata = {
  title: 'Dashboard-C',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning>
        <PagesProvider>{children}</PagesProvider>
        <div id='modal-root'></div>
      </body>
    </html>
  );
}
